export const PROJECT_LIST = [
    {
        title: 'React Tic-Tac-Toe',
        imgPath: '/src/assets/tic-tac-toe-react.png',
        description: 'Tic-Tac-Toe game built with React',
        tech: 'React, HTML, CSS, JavaScript',
        url: 'https://sean-cody-dev.github.io/tic-tac-toe-react/',
        repoUrl: 'https://github.com/sean-cody-dev/tic-tac-toe-react',
    },
    {
        title: 'Qwixx Clone',
        imgPath: '/src/assets/qwixx-clone.png',
        description: `Clone of popular card game Qwixx.`,
        tech: 'HTML, CSS, JavaScript',
        url: 'https://sean-cody-dev.github.io/qwixx-clone/',
        repoUrl: 'https://github.com/sean-cody-dev/qwixx-clone',
    },
    {
        title: 'Form Validator',
        imgPath: '/src/assets/form-validator.png',
        description: 'Simple form with validation using Constraint API',
        tech: 'HTML, CSS, JavaScript',
        url: 'https://sean-cody-dev.github.io/form-validator/',
        repoUrl: 'https://github.com/sean-cody-dev/form-validator',
    },
    {
        title: 'Quote Generator',
        imgPath: '/src/assets/quote-generator.png',
        description: 'Random quote generator using API fetch, featuring light and dark mode toggle',
        tech: 'HTML, CSS, JavaScript',
        url: 'https://sean-cody-dev.github.io/quote-generator/',
        repoUrl: 'https://github.com/sean-cody-dev/quote-generator',
    },
    {
        title: 'Infinite Scroll',
        imgPath: '/src/assets/infinite-scroll.png',
        description: 'Infinite image scroll using Unsplash API',
        tech: 'HTML, CSS, JavaScript',
        url: 'https://sean-cody-dev.github.io/infinite-scroll/',
        repoUrl: 'https://github.com/sean-cody-dev/infinite-scroll',
    },
    {
        title: 'Joke Teller',
        imgPath: '/src/assets/joke-teller.png',
        description: 'Random joke teller using Joke API and VoiceRSS API',
        tech: 'HTML, CSS, JavaScript',
        url: 'https://sean-cody-dev.github.io/joke-teller/',
        repoUrl: 'https://github.com/sean-cody-dev/joke-teller',
    },
];